export default {
  colorBlack: '#1b1c20',
  colorBlue: '#3850d9',
  colorFaintGray: '#d9dde5',
  colorGray: '#2c3436',
  colorMint: '#00a3a4',
  colorPurple: '#331e96',
  colorRed: '#fa4659',
  colorWhite: '#ffffff',
  colorLightBlue: '#e8eefd',
  colorLightGray: '#b9bed1',
  colorLightMint: '#14d0cd',
  colorLightPurple: '#a29bfe',
  colorLightRed: '#fccdd2',
  colorMiddleBlue: '#95c9ff',
  colorMiddleGray: '#78849e',
  colorMiddleMint: '#14d0cd',
  colorMiddlePurple: '#6c5ce7',
  colorMiddleRed: '#ff7676',
  fontFamilyBMJUA:
    "'BMJUA', -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  fontFamilyDoHyeon:
    "'Do Hyeon', -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  fontFamilyNotoSansKR:
    "'Noto Sans KR', -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  fontFamilyYeonsung:
    "'BMYEONSUNG', -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  fontFamilyJalnan:
    "'yg-jalnan', -apple-system, system-ui, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif",
  fontSizeTextL: '18px',
  fontSizeTextM: '16px',
  fontSizeTextS: '14px',
  fontSizeTextXL: '20px',
  fontSizeTextXS: '12px',
  fontSizeTextXXL: '22px',
  fontSizeTextXXS: '10px',
  fontSizeTitleL: '24px',
  fontSizeTitleM: '21px',
  fontSizeTitleS: '18px',
  fontSizeTitleXL: '36px',
  fontSizeTitleXS: '16px',
  fontSizeTitleXXL: '48px',
  fontSizeTitleXXS: '14px',
};
